export enum APP_STATE_ACTIONS {
    USER_LOGIN = 'USER_LOGIN',
    USER_LOGOUT = 'USER_LOGOUT'
}

export enum SHOPPING_LIST_ACTIONS {
    ADD_PRODUCT = 'ADD_PRODUCT',
    REMOVE_PRODUCT = 'REMOVE_PRODUCT',
    INCREASE_PRODUCT = 'INCREASE_PRODUCT',
    DECREASE_PRODUCT = 'DECREASE_PRODUCT',
    CHECK_PRODUCT = 'CHECK_PRODUCT',
    UNCHECK_PRODUCT = 'UNCHECK_PRODUCT',
    CLEAR_LIST = 'CLEAR_LIST',
    SET_LIST = 'SET_LIST',
}