export enum TASK {
  CONTROLLER = 'CONTROLLER',
  SERVICE = 'SERVICE',
  REPOSITORY = 'REPOSITORY',
}

export enum AUTH {
  CONTROLLER = 'CONTROLLER',
  SERVICE = 'AUTH_SERVICE',
  REPOSITORY = 'REPOSITORY',
}

export enum MAIN {
  BOOTSTRAP = 'BOOTSTRAP',
}
